### PR TITLE
fix: prettier config file name and format project

### PR DESCRIPTION
**Pull request by LRNZ09**
Fix prettier config not being detected and format project files

### CODE REVIEW

**Review by agustito37 — COMMENTED** [review]
Seems to be working 😄

**Comment by LRNZ09** [comment]
@agustito37 it should be ok now

**Comment by agustito37** [comment]
Hi, we should only be linting the code inside src I think and it seems to be linting all the root folder. WDYT?

**Comment by LRNZ09** [comment]
I have run the command `yarn prettier --write *.js src/**/*js` which I think it's ok

**Comment by agustito37** [comment]
It seems fine, but it shouldn't change the config files.

**Comment by LRNZ09** [comment]
It gives me an error for `demo/babel.config.js`, what should I do?

**Comment by agustito37** [comment]
Which error, can you share it, not sure what are you referring to.

**Comment by LRNZ09** [comment]
Before the commit, it gives me ```4:15  error  Replace `"babel-preset-expo"]` with `'babel-preset-expo'],`  prettier/prettier```
Maybe it should be added to `.eslintignore` too?

**Comment by agustito37** [comment]
That's my main concern, to linter things that we shouldn't. We should only be lining src/**/*.js. Why it is linting demo/; not sure, there should be a misconfiguration.

**Comment by LRNZ09** [comment]
That's because `.eslintignore` excludes everything except `src`, `demo`, and `tests` folders. I can fix it.

**Comment by agustito37** [comment]
Ok, I get it now, let's do this, maybe is a good thing to lint all the demo folder given the files are not inside a src folder. So if it is just the babel.config.js that needs changes, I don't see a problem to apply the lint on that file.

**Comment by LRNZ09** [comment]
What about the `tests` folder? Should we include it too?

**Comment by agustito37** [comment]
Yes, I think the test should be linted too.

**Comment by LRNZ09** [comment]
@agustito37 it should be everything ok now!

**Review by agustito37 — APPROVED** [review]

**Comment by agustito37** [comment]
Great I'll merge this @LRNZ09, thanks for your contribution!

**Pull request merged**
